export const movies = [
  {
    id: 1,
    titulo: "The Shawshank Redemption",
    genero: "Drama",
    anio: 1994,
    director: "Frank Darabont",
    likes: 2800000,
    portada: "https://m.media-amazon.com/images/M/MV5BYmVlNWFjODUtZDA2Yi00MmRkLTk5NWQtMGQ3MDJjYTRlZWFiXkEyXkFqcGc@._V1_.jpg",
  },
  {
    id: 2,
    titulo: "The Godfather",
    genero: "Crime, Drama",
    anio: 1972,
    director: "Francis Ford Coppola",
    likes: 2500000,
    portada: "https://m.media-amazon.com/images/M/MV5BOTFhMzgwNzQtNTYzMS00NDdlLWJkMjYtMGY3ZGY5NjZjYjliXkEyXkFqcGc@._V1_QL75_UX295_.jpg",
  },
  {
    id: 3,
    titulo: "The Dark Knight",
    genero: "Action, Crime, Drama",
    anio: 2008,
    director: "Christopher Nolan",
    likes: 2300000,
    portada: "https://www.lavanguardia.com/peliculas-series/images/movie/poster/2008/7/w1280/8QDQExnfNFOtabLDKqfDQuHDsIg.jpg",
  },
  {
    id: 4,
    titulo: "Forrest Gump",
    genero: "Drama, Romance",
    anio: 1994,
    director: "Robert Zemeckis",
    likes: 2100000,
    portada: "https://prodimage.images-bn.com/pimages/0032429317711_p0_v2_s600x595.jpg",
  },
  {
    id: 5,
    titulo: "Inception",
    genero: "Action, Adventure, Sci-Fi",
    anio: 2010,
    director: "Christopher Nolan",
    likes: 2100000,
    portada: "https://pics.filmaffinity.com/Origen-131981581-large.jpg",
  },
  {
    id: 6,
    titulo: "Fight Club",
    genero: "Drama",
    anio: 1999,
    director: "David Fincher",
    likes: 2000000,
    portada: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjptGkW4UwD3BdMJMcAPCcuYD9U9M8GJD3QQ76FIanqoxspZk2q9sdKXSOIx7yiQsF5T-ZdkTHUM21_AEN6vH2OXucUbTnIhQ4CEUbMtWr7TZ-FIklXl5vrGg1fl7vib3E2of5DWCGmE3H3/s2048/Club-de-la-lucha.jpg",
  },
  {
    id: 7,
    titulo: "The Matrix",
    genero: "Action, Sci-Fi",
    anio: 1999,
    director: "The Wachowskis",
    likes: 1900000,
    portada: "https://i0.wp.com/thebackdoortheatre.org/wp-content/uploads/2023/11/The_matrix.jpg?fit=374%2C560&ssl=1",
  },
  {
    id: 8,
    titulo: "The Lord of the Rings: The Return of the King",
    genero: "Action, Adventure, Drama",
    anio: 2003,
    director: "Peter Jackson",
    likes: 1800000,
    portada: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjTXWBpWJDl0dzhli20AeETW_n0A36m05s3_MfZwHfuEq6LFoOhVSvyQONft0vIjgbqpnJaysUIKtnwtieorK-3b3GJtFnQsDIuHBbCWVWHo2vGpiE0x9HDNoQDXXQSe2SbIKwG0g6czOFG/s1600/el_senor_de_los_anillos_la_comunidad_del_anillo-caratula.jpg",
  },
  {
    id: 9,

    titulo: "Pulp Fiction",
    genero: "Crime, Drama",
    anio: 1994,
    director: "Quentin Tarantino",
    likes: 1700000,
    portada: "https://i.pinimg.com/736x/da/40/91/da4091594426aebe733cd053a955ee14.jpg",
  },
  {
    id: 10,
    titulo: "Schindler's List",
    genero: "Biography, Drama, History",
    anio: 1993,
    director: "Steven Spielberg",
    likes: 1600000,
    portada: "https://pics.filmaffinity.com/La_lista_de_Schindler-991615190-large.jpg",
  },
  {
    id: 11,
    titulo: "The Silence of the Lambs",
    genero: "Crime, Drama, Thriller",
    anio: 1991,
    director: "Jonathan Demme",
    likes: 1500000,
    portada: "https://s3.amazonaws.com/criterion-production/films/46014912ca0c20592c472f5bbe33e4f8/L9AQ95Y7z2vOIUf1ntwvpZsZx3kp8B_large.jpg",
  },
  {
    id: 12,
    titulo: "Interstellar",
    genero: "Adventure, Drama, Sci-Fi",
    anio: 2014,
    director: "Christopher Nolan",
    likes: 1400000,
    portada: "https://m.media-amazon.com/images/I/91vIHsL-zjL._AC_UF894,1000_QL80_.jpg",
  },
  {
    id: 13,
    titulo: "Gladiator",
    genero: "Action, Adventure, Drama",
    anio: 2000,
    director: "Ridley Scott",
    likes: 1300000,
    portada: "https://www.lavanguardia.com/peliculas-series/images/movie/poster/2000/5/w1280/o6XhzKghQFliN49iE4M4RX94PTB.jpg"},
  {
    id: 14,
    titulo: "The Social Network",
    genero: "Biography, Drama",
    anio: 2010,
    director: "David Fincher",
    likes: 1200000,
    portada: "https://www.marketingdirecto.com/wp-content/uploads/2010/08/the-social-network.jpg",
  },
  {
    id: 15,
    titulo: "The Prestige",
    genero: "Drama, Mystery, Sci-Fi",
    anio: 2006,
    director: "Christopher Nolan",
    likes: 1100000,
    portada: "https://m.media-amazon.com/images/M/MV5BMGZkMGFiMDQtMTE5YS00OTk5LTk4MGQtYTAyOTZkZmQ2ZjAyXkEyXkFqcGc@._V1_.jpg",
  },
];

export default movies;
